# WhatATheme
markdown: kramdown

# URL of the Site
url: "https://KimJunyoung77.github.io"
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: "/WhatATheme"

# Title of the Site
title: Jay Portpolio
# Description of the Site
description: A customizable Jay portfolio theme
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/home.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: giim1017@naver.com
github_username:  KimJunyoung77

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Jay
# URL for the Image of the Author
author-image: https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
# 60 Words About the Author
author-about: 여기는 제이의 포트폴리오를 소개하는 공간입니다.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://KimJunyoung77.github.io

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: pretty

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
