# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Amy Elliott
# Description of the Site
description: I'm a Gameplay Programmer!
# URL of Image of the Site
site-image: /amy-portfolio/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Portfolio, Programmer, GameDev
# URL for the Image of custom Favicon
favicon-url: 

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: amy.elliott2002@yahoo.co.uk
twitter_username: AmyElliott_
instagram_username: amy.m.elliott
linkedin_username: amy-m-elliott
github_username:  AmyE123

# Google Analytics
google-analytics: G-SJTTGX1K8N

# Disqus
disqus-shortname: amy

# Name of the Author
author-name: Amy Elliott
# URL for the Image of the Author
author-image: https://onedrive.live.com/embed?resid=9594E849DC7FC39E%2160435&authkey=%21AJvq3Evp2_4AYZg&width=800&height=800
# 60 Words About the Author
author-about: "Hi! I'm Amy, a UK-based programmer. I love technical and creative experimentation, often participating in game jams and small projects. I enjoy exploring various genres and pushing my creative and technical boundaries. I'm always eager to learn, whether it's mastering game engines, diving into programming problems, or tackling fun projects with weird hardware. One of my goals is to inspire younger and diverse individuals to explore game development. I've mentored students, spoken at events, high schools, colleges and universities, and appeared as a panellist at events like the Women in Games Expo."
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/AmyE123

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:title/

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
